title: John K. Lindstedt, PhD
email: john.k.lindstedt@gmail.com
description: >-
cognitive science researcher,
async-online educator,
open source AI developer
baseurl: ""
url: "https://jackal37.github.io"
